/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import java.awt.*;
import modelo.Categoria;
import controlador.ctr_categoria;
import javax.swing.JOptionPane;
/**
 *
 * @author Renato
 */
public class inter_categoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form inter_categoria
     */
    public inter_categoria() {
        initComponents();
        this.setSize(new Dimension(400, 200));
        this.setTitle("Nueva categoria");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_descripcion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(400, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nueva Categoria");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Categoria: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        tf_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_descripcionActionPerformed(evt);
            }
        });
        getContentPane().add(tf_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 150, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        wallpaper.setText("llll");
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 390, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_descripcionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Categoria categoria=new Categoria();
        ctr_categoria controlCategoria=new ctr_categoria();
       
        //validar caqmpos vacios
        if(tf_descripcion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Complete todos los campos"); 
                   
        }else{
            if(!controlCategoria.existeCategoria(tf_descripcion.getText().trim())){
                 categoria.setDescripcion(tf_descripcion.getText().trim());
                 categoria.setEstado(1);
                 if(controlCategoria.guardar(categoria)){
                        JOptionPane.showMessageDialog(null, "Registro Guardado");
                 }else{
                        JOptionPane.showMessageDialog(null, "Error al guardar");
                    }
            }else{
                JOptionPane.showMessageDialog(null, "La categoria ya existe");
            }
            
            
        }
        //limpiar campo
        tf_descripcion.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tf_descripcion;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
