/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import conexion.Conexion;
import java.awt.*;
import java.sql.*;
import java.sql.SQLException;
import modelo.producto;
import controlador.ctr_producto;
import javax.swing.JOptionPane;
public class inter_producto extends javax.swing.JInternalFrame {

   public double pc;
   public double pv;
   String obtenerIdCategoriaCombo="";
    public inter_producto() {
        initComponents();
        this.setSize(new Dimension(400,300));
        this.setTitle("Nuevo producto");
        this.cargarComboCategorias();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_cantidad = new javax.swing.JTextField();
        tf_precioc = new javax.swing.JTextField();
        tf_descripcion = new javax.swing.JTextField();
        cb_categoria = new javax.swing.JComboBox<>();
        b_guardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tf_preciov = new javax.swing.JTextField();
        tf_iva = new javax.swing.JTextField();
        wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo producto: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad: ");
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 20));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Iva:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Descripcion: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio compra:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Categoria: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        tf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 160, -1));
        getContentPane().add(tf_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 160, -1));

        tf_precioc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_preciocActionPerformed(evt);
            }
        });
        getContentPane().add(tf_precioc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 160, -1));
        getContentPane().add(tf_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 160, -1));

        cb_categoria.setForeground(new java.awt.Color(255, 255, 255));
        cb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione categoria: ", "f", "f", "f" }));
        getContentPane().add(cb_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 160, -1));

        b_guardar.setText("Guardar");
        b_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(b_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Precio venta:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, -1));

        tf_preciov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_preciovActionPerformed(evt);
            }
        });
        getContentPane().add(tf_preciov, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 160, -1));

        tf_iva.setText("0.0");
        tf_iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ivaActionPerformed(evt);
            }
        });
        getContentPane().add(tf_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 160, -1));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreActionPerformed

    private void tf_preciocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_preciocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_preciocActionPerformed

    private void b_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarActionPerformed
        // TODO add your handling code here:
        
        producto prod=new producto();
        String iva="";
        ctr_producto ct_prod = new ctr_producto();
        String categoria="";
        //iva=cb_iva.getSelectedItem().toString().trim();
        categoria=cb_categoria.getSelectedItem().toString().trim();
        if(tf_nombre.getText().equals("") || tf_cantidad.getText().equals("") || tf_precioc.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
            tf_nombre.setBackground(Color.red);
            tf_cantidad.setBackground(Color.red);
            tf_precioc.setBackground(Color.red);
        }else{
            //consulta para ver si el producto ya existe
            if(!ct_prod.existeProducto(tf_nombre.getText().trim())){
                if(iva.equalsIgnoreCase("Seleccione iva: ")){
                    
                }else{
                    if(categoria.equalsIgnoreCase("Seleccione categoria: ")){
                        
                    }else{
                        try{
                            prod.setNombre(tf_nombre.getText().trim());
                            
                            double precioc=0.0; //para ver si pone ,
                            double preciov=0.0;
                            String precio_tfc="";
                            precio_tfc=tf_precioc.getText().trim();
                            String precio_tfv="";
                            precio_tfv=tf_preciov.getText().trim();
                            boolean aux=false;
                            //si el usuario ingresa (coma) como punto decimal lo trasformamos a punto
                            for(int i=0;i<precio_tfc.length();i++){
                                if(precio_tfc.charAt(i)==','){
                                    String precioNuevo=precio_tfc.replace(",", ".");
                                    precioc=Double.parseDouble(precioNuevo);
                                    aux=true;
                                }
                            }
                            for(int i=0;i<precio_tfv.length();i++){
                                if(precio_tfv.charAt(i)==','){
                                    String precioNuevov=precio_tfv.replace(",", ".");
                                    preciov=Double.parseDouble(precioNuevov);
                                    aux=true;
                                }
                            }
                            if(aux==true){
                                prod.setPrecioventa(precioc);
                                prod.setPreciocompra(preciov);
                            }else{
                                precioc=Double.parseDouble(precio_tfc);
                                prod.setPrecioventa(precioc);
                                preciov=Double.parseDouble(precio_tfv);
                                prod.setPrecioventa(preciov);
                            }
                            prod.setDescripcion(tf_descripcion.getText().trim());
                            
                            //id categoria - cargar metodo que tiene el id de la categoria
                            
                            this.idCategoria();
                            //prod.setIdCategoria(obtenerIdCategoriaCombo);
                            prod.setEstado(1);
                            
                            pc=Double.parseDouble(tf_precioc.getText());
                            pv=Double.parseDouble(tf_preciov.getText());
                            System.out.println(pc);
                            System.out.println(pv);
                            boolean resp=false;
                            inter_producto n=new inter_producto();
                            Connection cone=Conexion.conectar();
                            try{
                                PreparedStatement consulta=cone.prepareStatement("insert into tb_producto_3 values(?,?,?,?,?,?,?,?,?)");
                                consulta.setInt(1, 0);//id
                                consulta.setString(2, tf_nombre.getText().trim());
                                consulta.setInt(3, Integer.parseInt(tf_cantidad.getText().trim()));
                                consulta.setDouble(4, pc);
                                consulta.setString(5, tf_descripcion.getText().trim());
                                consulta.setDouble(6, pv);
                                consulta.setInt(7, 0);
                                consulta.setString(8, cb_categoria.getSelectedItem().toString());
                                consulta.setInt(9, prod.getIdProducto());
                                if(consulta.executeUpdate()>0){
                                    resp=true;
                                }
                                cone.close();
                            }catch(SQLException e){
                                System.out.println("Error al guardar producto " + e);
                            }
                            this.Limpiar();
                            
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(null, "Error en: " );
                        }
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "El producto ya existe en la baase de datos");
            }
        }
    }//GEN-LAST:event_b_guardarActionPerformed

    private void tf_preciovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_preciovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_preciovActionPerformed

    private void tf_ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ivaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_guardar;
    private javax.swing.JComboBox<String> cb_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tf_cantidad;
    private javax.swing.JTextField tf_descripcion;
    public javax.swing.JTextField tf_iva;
    private javax.swing.JTextField tf_nombre;
    public javax.swing.JTextField tf_precioc;
    public javax.swing.JTextField tf_preciov;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables

    
    private void Limpiar(){
        tf_nombre.setText("");
        tf_cantidad.setText("");
        tf_descripcion.setText("");
        tf_precioc.setText("");
        tf_preciov.setText("");
    }
    //metodo para cargar categorias
    
    private void cargarComboCategorias(){
        Connection cn=Conexion.conectar();
        String sql="select * from tb_categorias";
        Statement st;
        try{
            st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            cb_categoria.removeAllItems();
            cb_categoria.addItem("Seleccione categoria: ");
            while(rs.next()){
                cb_categoria.addItem(rs.getString("descripcion"));
            }
            cn.close();
        }catch(SQLException e){
            System.out.print("Error al cargar categorias" + e);
        }
    }
    //metodo para obtener cvatgeoria
    private String idCategoria(){
        String sql="select * from tb_categorias where descripcion= '" + this.cb_categoria.getSelectedItem().toString() + "'";
        Statement st;
         try{
            Connection cn=Conexion.conectar();
            st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
           
            while(rs.next()){
                obtenerIdCategoriaCombo=rs.getString("idCategoria");
            }
            cn.close();
        }catch(SQLException e){
            System.out.print("Error al obetener id categorias" + e);
        }
        return obtenerIdCategoriaCombo;
    }

}
